const { model } = require("mongoose");

const ideas = [
  "todo app",
  "blog app",
  "social media app",
  "chat app",
  "weather app",
  "news app",
  "music app",
  "video app",
  "e-commerce app",
  "online store app",
  "online shopping app",
  "online payment app",
  "online banking app",
  "online ticket booking app",
  "online food ordering app",
  "Quote generator app",
  "image gallery app",
  "basic calculator app",
  "currency converter app",
  "recipe app",
  "restaurant app",
  "counter app",
  "stopwatch app",
  "timer app",
  "quiz app",
  "flashcard app",
  "testimonials app",
  "filter app",
  "Form validation app",
  "to do list app",
  "notes app",
  "URL shortener app",
  "password generator app",
  "image slider app",
  "budget app",
  "random joke app",
  "weather app",
  "analytics app",
  "analog clock app",
  "BMI calculator app",
  "Tip calculator app",
  "word counter app",
  "text to speech app",
  "speech to text app",
  "real time chat app",
  "real time video chat app",
  "Node JS API",
  "Node JS CRUD API",
  "Node JS Authentication API",
  "Node JS JWT Authentication API",
  "Node JS CRUD API with Authentication",
  "Node JS book directory",
  "Node JS Email sending app",
  "Discord Bot",
  "Web Scrapper",
  "NLP Chatbot",
  "RSS Feed Reader",
  "Image to PDF Converter",
  "PDF to Image Converter",
  "Social Network",
  "online Photo college",
  "Road trip planner",
  "Daily sleep tracker",
  "minute to win it game",
  "2D game",
  "Area calculator",
  "Power calculator",
  "blackjack game",
  "Tic Tac Toe game",
  "Rock Paper Scissors game",
  "Hangman game",
  "Simon game",
  "Pong game",
  "Snake game",
  "Tetris game",
  "Minesweeper game",
  "Connect Four game",
  "Battleship game",
  "Pacman game",
  "Space Invaders game",
  "Breakout game",
  "Flappy Bird game",
  "2048 game",
  "Chess game",
  "Checkers game",
  "Reversi game",
  "Frame per second counter",
  "JS drum kit",
  "maze game",
  "Sorting algorithm visualizer",
  "Pathfinding algorithm visualizer",
  "WhatsApp API",
  "word scramble game",
  "wordle game",
  "star rating system",
  "DOM Array Methods",
  "DOM input validator",
  "DOM interaction with local storage",
  "Screeen recorder",
  "Random user generator",
  "Github finder",
  "Github profiles",
  "URL Validator",
  "Referral system",
  "Referral Generator",
  "Referral Tracker",
  "User Information Encryption",
  "User Information Decryption",
  "User Information Hashing",
  "Infinite Scroll",
  "Speech Synthesis",
  "ASCII Art Generator",
  "File Uploader",
  "File Downloader",
  "File Reader",
  "File Writer",
  "File renamer",
  "HTTP Request Logger",
  "Faker JS",
  "JSON to CSV Converter",
  "CSV to JSON Converter",
  "Date and Time Formatter",
  "Timezone Converter",
  "TLS Certificate Checker",
  "IP Address Tracker",
  "IP Address Geolocation",
  "Passport Authentication",
  "Password Strength Checker",
  "Video compressor",
  "User status",
  "Data visualization",
  "Data visualization with D3",
  "Data visualization with Chart.js",
  "Calendar",
];

module.exports = ideas;
